Parameters:
  KeyName: 
    Type: AWS::EC2::KeyPair::KeyName
  VpcId:
    Description: ID of an existing Virtual Private Cloud (VPC).
    Type: 'AWS::EC2::VPC::Id'


Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName 
      ImageId: ami-0e2c8caa4b6378d8c
      InstanceType: t2.micro
      SecurityGroupIds: !Ref InstanceSecurityGroup

Outputs: 
  Instance: 
    Value: !Ref MyInstance  
  InstancePub: 
    Value: !GetAtt MyInstance.PublicIp