Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  
  VpcBlock:
    Type: String
    Default: 10.0.0.0/16
  
  Subnet1:
    Type: String
    Default: 10.0.0.0/17

  Subnet2:
    Type: String
    Default: 10.0.128.0/17

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-zdq7qdtwmu1f-us-east-1.s3.us-east-1.amazonaws.com/vpc.yml
      Parameters:
        VpcCIDR: !Ref VpcBlock
        PublicSubnetCIDR: !Ref Subnet1
        PrivateSubnetCIDR: !Ref Subnet2
        
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: ami-0e2c8caa4b6378d8c
      InstanceType: t2.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !GetAtt VpcStack.Outputs.PublicSubnet
